[package]
name = "delve-shim-dap"
version = "0.1.0"
edition = "2024"

[dependencies]
debugserver-types = "0.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
